name: Deploy to Azure Static Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep template
      run: |
        az deployment sub create \
          --name "swa-deployment-$(date +%s)" \
          --location westus2 \
          --template-file infra/main.bicep \
          --parameters \
            resourceGroupName=${{ secrets.RESOURCE_GROUP_NAME }} \
            location=westus2 \
            staticWebAppName=${{ secrets.STATIC_WEB_APP_NAME }}

    - name: Get Static Web App deployment token
      id: get-token
      run: |
        token=$(az staticwebapp secrets list \
          --name "${{ secrets.STATIC_WEB_APP_NAME }}" \
          --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
          --query "properties.apiKey" \
          -o tsv)
        {
          echo "token=$token"
        } >> "$GITHUB_OUTPUT"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ steps.get-token.outputs.token }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        api_location: ""
        output_location: "dist"
